version : '3.3'
services:
  douyin:
    container_name: douyin
    image: douyin:latest
    build:
      context: .  # ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./conf:/etc/douyin
      - ./data:/var/lib/douyin
    #command:
    #  - "/go/bin/douyin /etc/douyin/app.json"
    networks:
      - middleware_default

networks:
  middleware_default:
    external: true